apiVersion: v1
kind: Pod
metadata:
  name: <POD_NAME>
  labels:
    app: lab3
  namespace: <YOUR_PROJECT>
spec:
  containers:
  - name: busybox
    image: busybox
    command: ['sh', '-c', 'while :; do sleep 10; done']
    volumeMounts:
      - name: shared-storage
        mountPath: /home
  volumes:
  - name: shared-storage
    persistentVolumeClaim:
      claimName: shared-pvc

